tensordot/syntaxdot

- syntaxdot/src/dataset.rs
In both cases, two lifetimes 'a and 'ds were used, which were
bound anyway. This change replaces them by one lifetime.
> Simplify two lifetime annotations in the dataset module

- syntaxdot-transformers/src/hdf5_model.rs
- syntaxdot-transformers/src/layers.rs
- syntaxdot-transformers/src/models/bert/mod.rs
- syntaxdot-transformers/src/models/mod.rs
- syntaxdot-transformers/src/models/squeeze_bert/mod.rs
- syntaxdot-transformers/utils/pytorch-squeezetorch-to-hdf5.py
- syntaxdot/src/config.rs
- syntaxdot/src/model/bert.rs
The SqueezeBERT model replaces the matrix multiplications in the self-attention
mechanism and feed-forwared layers by grouped convolutions. This results in a
smaller number of parameters and better computational performance.
> Add the SqueezeBERT model

- syntaxdot-transformers/src/models/mod.rs
- syntaxdot-transformers/src/models/squeeze_albert/mod.rs
- syntaxdot/src/config.rs
- syntaxdot/src/error.rs
- syntaxdot/src/model/bert.rs
This model combines SqueezeBERT (Iandola et al., 2020) and
ALBERT (Lan et al., 2020):
* SqueezeBERT replaces most matrix multiplications by grouped
convolutions, resulting in smaller models and higher inference
speeds.
* ALBERT allows layers to share parameters and decouples the
embedding size from the hidden state size. Both result in
smaller models.
Combined, your models can be even smaller and faster.
> Add the SqueezeAlbert model

- scripts/test-all.sh
- syntaxdot-tokenizers/Cargo.toml
- syntaxdot-tokenizers/src/albert.rs
- syntaxdot-tokenizers/src/bert.rs
- syntaxdot-tokenizers/src/xlm_roberta.rs
- syntaxdot/Cargo.toml
These were not properly migrated when the tokenizers were moved to the
syntaxdot-tokenizers crate.
> Fix tokenizer model tests

- Cargo.lock
- syntaxdot-encoders/Cargo.toml
- syntaxdot-encoders/src/lemma/edit_tree.rs
- syntaxdot-encoders/src/lemma/encoder.rs
- syntaxdot-encoders/src/lemma/mod.rs
- syntaxdot-encoders/src/lemma/tdz.rs
- syntaxdot/Cargo.toml
- syntaxdot/src/encoders/encoders.rs
- The crate is small and this allows us to make changes without
waiting for crates.io uploads.
- Remove code that we do not need in syntaxdot-encoders.
- Some small cleanups.
> Ingest edit_tree crate in syntaxdot-encoders

- CHANGELOG.md
- syntaxdot-tokenizers/src/bert.rs
- syntaxdot-tokenizers/src/lib.rs
Implementations of `Tokenizer` are now required to put a piece that marks the
beginning of a sentence before the first token piece. `BertTokenizer` was the
only tokenizer that did not fulfill this requirement. `BertTokenizer` is
updated to insert the `[CLS]` piece as a beginning of sentence marker.
**Warning:** this breaks existing models with `tokenizer = "bert"`,
which should be retrained.
> Require tokenizers to add a BOS piece

- syntaxdot-transformers/src/lib.rs
- syntaxdot-transformers/src/loss.rs
- syntaxdot-transformers/src/scalar_weighting.rs
We use our own cross-entropy loss implementation for label smoothing.
This was implemented as a function in the scalar_weighting module. Since
we label smoothing for training dependency relation prediction, refactor
this function into a Torch module.
> Refactor cross-entropy loss function to a (Torch) module

- syntaxdot-cli/src/traits.rs
- syntaxdot/src/model/biaffine_dependency_layer.rs
- syntaxdot/src/model/mod.rs
This layer computes, given an encoder's hidden states, the head score
matrix and relation score tensor.
> Add a biaffine dependency layer

- syntaxdot-cli/src/io.rs
- syntaxdot-cli/src/subcommands/distill.rs
- syntaxdot-cli/src/subcommands/finetune.rs
- syntaxdot-transformers/src/loss.rs
- syntaxdot-transformers/src/models/layer_output.rs
- syntaxdot-transformers/src/scalar_weighting.rs
- syntaxdot/src/config.rs
- syntaxdot/src/dataset/tensor_iter.rs
- syntaxdot/src/model/bert.rs
- syntaxdot/src/model/biaffine_dependency_layer.rs
- syntaxdot/src/model/mod.rs
- syntaxdot/src/model/pooling.rs
- syntaxdot/src/model/seq_classifiers.rs
- syntaxdot/src/tagger/mod.rs
- syntaxdot/src/tensor.rs
- syntaxdot/testdata/sticker.conf
This change adds a data type PiecePooler that is used by BertModel to
pool the pieces of a token after encoding of the input. This has
several benefits:
- Every layer after the pooler can assume that their input consists of
token representations. This simplifies those layers, because they do
not have to mask out non-initial pieces.
- It opens up the possibility to implement and experiment with
different pooling functions.
Currently, only one pooler is available: PiecePooler::Discard. This
pooler uses the initial piece of a token as the token representation
and discards all continuation pieces. It results in the same
representations being used prior to this change and is therefore
compatible with existing SyntaxDot 0.3 models
With this change, it also became easy to implement label …
> Add basic support for token pooling

- syntaxdot-cli/src/subcommands/distill.rs
- syntaxdot-cli/src/subcommands/finetune.rs
- syntaxdot/src/model/bert.rs
- syntaxdot/src/model/biaffine_dependency_layer.rs
- syntaxdot/src/model/pooling.rs
- syntaxdot/src/model/seq_classifiers.rs
- syntaxdot/src/tagger/mod.rs
- syntaxdot/src/tensor.rs
- syntaxdot/src/util.rs
These types wrap Tensor and help to avoid confusion between passing
different types of tensors to methods. They also provide some
convenience methods to avoid ad-hoc conversions.
> Introduce TokenOffsets, TokenMask, and SequenceLength wrappers

- CHANGELOG.md
- syntaxdot-cli/src/subcommands/distill.rs
- syntaxdot-cli/src/subcommands/finetune.rs
- syntaxdot/src/dataset/tensor_iter.rs
- syntaxdot/src/model/bert.rs
- syntaxdot/src/model/pooling.rs
- syntaxdot/src/tagger/mod.rs
- syntaxdot/src/tensor.rs
This pooler takes the mean of all the representations of the pieces in
a token as the token's representation.
> Add mean pooler for token representations

- syntaxdot-cli/src/io.rs
- syntaxdot-cli/src/subcommands/distill.rs
By default, the student model uses the teacher's softmaxes for
training. The distill subcommand already provided the option to use
attention loss as an additional loss. However, attention loss only
works when the student and the teacher have the same tokenization
and number of layers.
This change adds an additional optional loss, that computes the mean
squared error of the teacher's and the student's hidden states. A
linear transformation is learned for mapping the student's space to
the teacher's space, which is particularly useful if the student and
the teacher use different dimensionalities. Additionally, a layer
mapping is specified to handle the case where the number of teacher
and student layers differ. For example,
```
--hidden-loss 0:0,2:1,4:2,6:3,8:4,10:5,12:6
```
Maps layers 0 …
> distill: add support for hidden layer loss

- build-support/crate-overrides.nix
- flake.lock
- flake.nix
* Fix linkage in the `syntaxdotWithCuda` package.
* Switch back to the `nixpkg-unstable` channel, now that it has
libtorch 1.8.0.
> nix: fix syntaxdotWithCuda build, switch to nixpkgs-unstable

- CHANGELOG.md
- syntaxdot-encoders/src/depseq/error.rs
- syntaxdot-encoders/src/depseq/mod.rs
- syntaxdot-encoders/src/depseq/post_processing.rs
- syntaxdot-encoders/src/depseq/relative_pos.rs
- syntaxdot-encoders/src/lemma/edit_tree.rs
- syntaxdot-summary/src/event_writer.rs
- syntaxdot-summary/src/record_writer.rs
- syntaxdot-transformers/src/activations.rs
- syntaxdot-transformers/src/models/bert/layer.rs
- syntaxdot/src/config.rs
- syntaxdot/src/dataset/conll.rs
- syntaxdot/src/dataset/plaintext.rs
- syntaxdot/src/encoders/config.rs
- syntaxdot/src/encoders/encoders.rs
- syntaxdot/src/error.rs
- syntaxdot/src/tagger/mod.rs
This ensures that sequence label decoders such as TdzLemma have access
to dependency labels.
> Apply biaffine decoding before sequence labeling

- .github/workflows/rust.yml
We use the latest stable Rust in CI for rustfmt, clippy, and tests. This
has the downside that PRs are rejected when there is a new clippy
version with new lints that fire in unrelated parts of the project.
This change pins the clippy job to a particular Rust version. We
can then update clippy (and fix issues) separately from other PRs.
> CI: Pin the Rust version for clippy

- Cargo.lock
- syntaxdot-cli/Cargo.toml
- syntaxdot-cli/src/sent_proc.rs
- syntaxdot-cli/src/subcommands/annotate.rs
SyntaxDot has so far used PyTorch inter/intraop parallelization. This
change adds support for parallelization at the batch level.  Batch-level
parallelization can be enabled with the `annotation-threads`
command-line option of `sticker annotate`.
For optimal performance, the `interop-threads` and `intraop-threads`
options should be set to 1.
Performance comparison on a Ryzen 3700X, Dutch medium UD model:
interop-threads = 4, intraop-threads = 4, annotation-threads = 1:
Processed 13028 sentences, 228 sents/s, 305073 pieces, 5333 pieces/s
interop-threads = 1, intraop-threads = 1, annotation-threads = 4:
Processed 13028 sentences, 247 sents/s, 305073 pieces, 5779 pieces/s
> Add support for parallelizing annotation at the batch level

- CHANGELOG.md
- syntaxdot-cli/src/subcommands/annotate.rs
This is faster for all models, both on AMD Ryzen and Apple M1.
> Use 1 inter/intraop thread, 4 annotation threads

- syntaxdot-transformers/src/activations.rs
- syntaxdot-transformers/src/models/bert/layer.rs
This is primarily useful in distillation, to distill into a model
that uses the ReLU activation for the position-wise feed-forward layers.
> Add the ReLU activation

- CHANGELOG.md
- syntaxdot-cli/src/sent_proc.rs
- syntaxdot-cli/src/subcommands/annotate.rs
- syntaxdot-tokenizers/src/lib.rs
Before this change, the batch size (`--batch-size`) was specified as the
number of sentences per batch. Since sentences are sorted by length
before batching, annotation is performed on batches with roughly
equisized sequences. However, later batches required more computations
per batch due to longer sequence lengths.
This change replaces the `--batch-size` option by the
`--max-batch-pieces` option. This option specifies the number of
word/sentence pieces that a batch should contain. SyntaxDot annotation
creates batches that contains at most that number of pieces. The only
exception are single sentences that are longer than the maximum number
of batch pieces.
With this change, annotating each batch is approximately the same amount
of work. This leads to approximately 10% increase in …
> Use dynamic batch sizes

- syntaxdot-transformers/src/activations.rs
- syntaxdot-transformers/src/error.rs
- syntaxdot-transformers/src/models/albert/config.rs
- syntaxdot-transformers/src/models/albert/embeddings.rs
- syntaxdot-transformers/src/models/albert/encoder.rs
- syntaxdot-transformers/src/models/bert/config.rs
- syntaxdot-transformers/src/models/bert/embeddings.rs
- syntaxdot-transformers/src/models/bert/encoder.rs
- syntaxdot-transformers/src/models/bert/layer.rs
- syntaxdot-transformers/src/models/bert/mod.rs
- syntaxdot-transformers/src/models/roberta/mod.rs
- syntaxdot-transformers/src/models/sinusoidal/mod.rs
- syntaxdot-transformers/src/models/squeeze_albert/mod.rs
- syntaxdot-transformers/src/models/squeeze_bert/config.rs
- syntaxdot-transformers/src/models/squeeze_bert/embeddings.rs
- syntaxdot-transformers/src/models/squeeze_bert/encoder.rs
- syntaxdot-transformers/src/models/squeeze_bert/layer.rs
- syntaxdot/src/config.rs
Before this change, each activation function was a separate struct that
implemented the `Activation` trait. Despite this genericity, the
activation functions were not extendable outside the transformers crate,
since in order to parse the activation function string from the
pretrained model configuration, we need to know about all available
activation functions.
This change replaces the structs by a single `Activation` enum. This
simplifies some code across the crate.
> Implement activation functions as an enum

- CHANGELOG.md
- syntaxdot-transformers/src/activations.rs
- syntaxdot-transformers/src/lib.rs
- syntaxdot/src/config.rs
- syntaxdot/src/model/biaffine_dependency_layer.rs
The default activation function is set to GELU for compatibility with
existing SyntaxDot configuration files.
> Make the activation for the biaffine feed-forward layers configurable

- syntaxdot-encoders/src/dependency/mod.rs
The `mst` module was not visible. Make it public again, but hide the module
from documentation.
> Fix the MST benchmark

- Cargo.lock
- syntaxdot/Cargo.toml
- syntaxdot/src/util.rs
Avoids dependency on both rand 0.7 and 0.8.
> Update to rand 0.8 in the syntaxdot crate

- CHANGELOG.md
- syntaxdot-tokenizers/src/xlm_roberta.rs
We were erroneously using sentencepiece's ID for unknown pieces (0), this ID corresponds to the `<s>` embedding in XLM-R. Fix this by replacing the ID by fairseq's ID for unknown pieces (3).
I don't see any difference when finetuning new Dutch models. It's possible that we never have unknown pieces for Dutch.
At any rate, this requires retraining of models for languages where the unknown piece is used.
> XlmRobertaTokenizer: replace sentencepiece unk id by fairseq's

- CHANGELOG.md
- syntaxdot-cli/src/subcommands/distill.rs
- syntaxdot-encoders/src/dependency/encoder.rs
- syntaxdot-transformers/src/layers.rs
- syntaxdot/src/model/biaffine_dependency_layer.rs
- syntaxdot/src/optimizers/grad_scale.rs
- syntaxdot/src/tagger/mod.rs
Before this change, we would use the following layers in the biaffine parser:
1. Pairwise biaffine layer for predicting heads. Output: `[batch_size, seq_len, seq_len]`
2. Pairwise biaffine layer for predicting dependency labels. Output: `[batch_size, seq_len, seq_len, n_rels]`
We would first MST-decode the output of (1) to find the heads. Then we would use the heads to gather the relevant relation predictions from (2). This change replaces (2) by:
2b. Biaffine layer for predicting dependencies. Output: `[batch_size, seq_len, n_rels]`
To make (2b) effective, we give it as the input the dependent representations of each tokens and the head representations gathered from the MST-decoded output of (1).
The new approach is mathematically equivalent to the old one, but is simpler and a bit …
> Simplify relation prediction in the biaffine parser

- Cargo.lock
This version fixes Linux AArch64 builds.
> Update sentencepiece dependency to 0.8.2

- Cargo.lock
This removes the last dependency under the Blue Oak Model License.
> Update numberer to 0.2.1

- syntaxdot-cli/src/subcommands/distill.rs
The implicit expansion emitted a Torch warning in each call.
> Fix implicit expansion when computing head logit mask
